FROM postgres:11

# Criar diretório para os scripts de inicialização
RUN mkdir -p /docker-entrypoint-initdb.d

# Copiar o script SQL para inicialização do banco
COPY ./src/connection/init.sql /docker-entrypoint-initdb.d/init.sql

# Ajustar permissões para garantir que o Postgres consiga ler o script
RUN chmod 644 /docker-entrypoint-initdb.d/init.sql

# Expor a porta padrão do PostgreSQL
EXPOSE 5432

# Comando padrão de entrada
CMD ["postgres"]
