FROM golang:1.22.3

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY ./src ./src
COPY ./main.go ./
COPY ./.env ./
COPY ./request ./request
COPY ./response ./response
COPY ./routers ./routers
COPY ./server ./server

RUN go build -o main .

EXPOSE 8000

CMD ["./main"]
