FROM golang:1.22.3

WORKDIR /app

COPY personal-registration/go.mod go.sum ./

RUN go mod download

COPY personal-registration/src ./src
COPY personal-registration/main.go ./
COPY personal-registration/.env ./
COPY personal-registration/request ./request
COPY personal-registration/response ./response
COPY personal-registration/routers ./routers
COPY personal-registration/server ./server

RUN go build -o main .

EXPOSE 8000

CMD ["./main"]
